kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer
  namespace: app
subjects:
- kind: ServiceAccount
  name: developer
  apiGroup: ""
roleRef:
  kind: Role
  name: developer
  apiGroup: ""