kind: Service
apiVersion: v1
metadata:
  name: ktor-app
  namespace: app
  labels:
    app: ktor-app
    version: 0.0.3
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: ktor-app
    app.kubernetes.io/name: ktor-app
  type:  LoadBalancer
